### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by rakaramos** [objcio/articles#108]
Image links are broken, could you please fix that?

**Comment by chriseidhof** [comment]
Hi @rakaramos , which article are you referring too? Here they seem to work fine!

**Comment by rakaramos** [comment]
@chriseidhof, for example:
2014-05-08-animating-custom-layer-properties
This link is broken: https://github.com/objcio/articles/blob/master/images/issue-12/clock.gif

**Comment by rakaramos** [comment]
Im downloading all the issues to convert them to Kindle format

**Comment by chriseidhof** [comment]
@rakaramos the images are not in that repo. They do work:

http://www.objc.io/issue-12/animating-custom-layer-properties.html

**Comment by rakaramos** [comment]
thanks @chriseidhof, I think I can workaround those links in .md files
