### ISSUE TITLE
issue5-4-from-NSURLConnection-to-NSURLSession 's issue.

### ISSUE THREAD

**Issue by hayyyyyyden** [objcio/articles#24]
in the paragraph "Download requests take a request as well...." of section `Constructors` in article [issue-5-4](https://github.com/objcio/articles/blob/master/2013-10-08-from-nsurlconnection-to-nsurlsession.md) I found something hard to be understood.
1. it says in the last: _"...the completion handler to move the file from its temporary location to a permanent location, which is then the **return value of the block**: "._  But the block here actually has **no return value**. so the code below will not be compilable. 
2. I also don't get the idea of the code of the block below that is using the `[response URL]`  instead of the return value `NSURL * location`. isn't the latter to be the actual temp file's URL?

**Comment by zixindedioashi** [comment]
o,o,soga
